In [31]:
import pandas as pd

files = [
    "visual_qa_batch1_rows0-49.csv",
    "visual_qa_batch2_rows50-99.csv",
    "visual_qa_batch3_rows100-149.csv",
    "visual_qa_batch4_rows150-199.csv",
    "visual_qa_rows200_to_end.csv"
    
]

dfs = []

for file in files:
    temp = pd.read_csv(file)
    dfs.append(temp)

final_df = pd.concat(dfs, ignore_index=True)
final_df = final_df.drop_duplicates().reset_index(drop=True)
final_df = final_df.drop(columns=["question_num"], errors="ignore")

final_df.to_csv("visual_qa_all_concatenated.csv", index=False)

print("Done!")
print("Total rows:", len(final_df))
print("Columns:", final_df.columns.tolist())
final_df

Done!
Total rows: 48065
Columns: ['image_path', 'image_url', 'source', 'topic', 'caption', 'question', 'answer']

,image_path,image_url,source,topic,caption,question,answer
0,dataset_images/pexels_person_1_0.jpg,https://images.pexels.com/photos/10078860/pexe...,pexels,person,grayscale portrait of a confident young man wi...,What is the man's posture in the image?,He has his arms crossed.
1,dataset_images/pexels_person_1_0.jpg,https://images.pexels.com/photos/10078860/pexe...,pexels,person,grayscale portrait of a confident young man wi...,Is the image in color or black and white?,The image is in grayscale (black and white).
2,dataset_images/pexels_person_1_0.jpg,https://images.pexels.com/photos/10078860/pexe...,pexels,person,grayscale portrait of a confident young man wi...,What is the expression on the man's face?,He has a subtle smile.
3,dataset_images/pexels_person_1_0.jpg,https://images.pexels.com/photos/10078860/pexe...,pexels,person,grayscale portrait of a confident young man wi...,How would you describe the man's appearance?,He appears confident and young.
4,dataset_images/pexels_person_1_0.jpg,https://images.pexels.com/photos/10078860/pexe...,pexels,person,grayscale portrait of a confident young man wi...,What does the man's body language suggest?,His crossed arms and subtle smile suggest conf...
...,...,...,...,...,...,...,...
48060,dataset_images/unsplash_clock_1_29.jpg,https://images.unsplash.com/photo-151285624666...,unsplash,clock,grayscale photography of clock,What is the main subject of the image?,The main subject is a grayscale photography of...
48061,dataset_images/unsplash_clock_1_29.jpg,https://images.unsplash.com/photo-151285624666...,unsplash,clock,grayscale photography of clock,What details are visible in the image?,The image features grayscale photography of cl...
48062,dataset_images/unsplash_clock_1_29.jpg,https://images.unsplash.com/photo-151285624666...,unsplash,clock,grayscale photography of clock,What is the dominant color in the image?,Grayscale photography of clock is the dominant...
48063,dataset_images/unsplash_clock_1_29.jpg,https://images.unsplash.com/photo-151285624666...,unsplash,clock,grayscale photography of clock,Is the image in color?,"No, it is a grayscale photography of clock image."
48064,dataset_images/unsplash_clock_1_29.jpg,https://images.unsplash.com/photo-151285624666...,unsplash,clock,grayscale photography of clock,What is the overall theme?,The theme is grayscale photography of clock.

In [32]:
['image_path', 'image_url', 'source', 'topic', 'caption', 'question', 'answer']
['image_id', 'caption', 'question', 'answer', 'source', 'image_url', 'topic']

df_GPT = pd.read_csv('high_quality_visual_qa.csv')

df_GPT["image_path"] = final_df["image_path"]
df_GPT.drop(columns=["image_id"], inplace=True, errors="ignore")
df_GPT["source"] = final_df["source"]
df_GPT["image_url"] = final_df["image_url"]
df_GPT["topic"] = final_df["topic"]

In [33]:
df_GPT.columns.tolist()

['caption', 'question', 'answer', 'image_path', 'source', 'image_url', 'topic']

In [34]:
df_GPT

,caption,question,answer,image_path,source,image_url,topic
0,grayscale portrait of a confident young man wi...,What details can be observed in the picture?,Several visible details include grayscale port...,dataset_images/pexels_person_1_0.jpg,pexels,https://images.pexels.com/photos/10078860/pexe...,person
1,grayscale portrait of a confident young man wi...,What is the focus of this image?,The focus of the image is grayscale portrait o...,dataset_images/pexels_person_1_0.jpg,pexels,https://images.pexels.com/photos/10078860/pexe...,person
2,grayscale portrait of a confident young man wi...,What kind of environment is shown in the image?,The environment shown includes grayscale portr...,dataset_images/pexels_person_1_0.jpg,pexels,https://images.pexels.com/photos/10078860/pexe...,person
3,grayscale portrait of a confident young man wi...,What is happening in the photograph?,The photograph depicts grayscale portrait of a...,dataset_images/pexels_person_1_0.jpg,pexels,https://images.pexels.com/photos/10078860/pexe...,person
4,grayscale portrait of a confident young man wi...,What can you infer from the scene?,It can be inferred that the image shows graysc...,dataset_images/pexels_person_1_0.jpg,pexels,https://images.pexels.com/photos/10078860/pexe...,person
...,...,...,...,...,...,...,...
48060,grayscale photography of clock,Can you describe what is visible in the image?,The image shows grayscale photography of clock.,dataset_images/unsplash_clock_1_29.jpg,unsplash,https://images.unsplash.com/photo-151285624666...,clock
48061,grayscale photography of clock,What elements are clearly visible in the image?,The image clearly contains grayscale photograp...,dataset_images/unsplash_clock_1_29.jpg,unsplash,https://images.unsplash.com/photo-151285624666...,clock
48062,grayscale photography of clock,What stands out the most in this picture?,A notable feature in the image is grayscale ph...,dataset_images/unsplash_clock_1_29.jpg,unsplash,https://images.unsplash.com/photo-151285624666...,clock
48063,grayscale photography of clock,What can you infer from the scene?,It can be inferred that the image shows graysc...,dataset_images/unsplash_clock_1_29.jpg,unsplash,https://images.unsplash.com/photo-151285624666...,clock
48064,grayscale photography of clock,Describe the overall mood or scene of the image.,The overall scene reflects grayscale photograp...,dataset_images/unsplash_clock_1_29.jpg,unsplash,https://images.unsplash.com/photo-151285624666...,clock

In [36]:
import pandas as pd

file1 = "visual_qa_all_concatenated.csv"

df1 = pd.read_csv(file1)

df2 = df_GPT.copy()

final_cols = [
    "image_path",
    "image_url",
    "source",
    "topic",
    "caption",
    "question",
    "answer"
]

for col in final_cols:
    if col not in df1.columns:
        df1[col] = ""

    if col not in df2.columns:
        df2[col] = ""

df1 = df1[final_cols]
df2 = df2[final_cols]

final_df = pd.concat([df1, df2], ignore_index=True)

final_df.to_csv("final_visual_qa_dataset.csv", index=False)

print("Done!")
print(final_df.shape)
print(final_df.columns.tolist())
final_df

Done!
(96130, 7)
['image_path', 'image_url', 'source', 'topic', 'caption', 'question', 'answer']

,image_path,image_url,source,topic,caption,question,answer
0,dataset_images/pexels_person_1_0.jpg,https://images.pexels.com/photos/10078860/pexe...,pexels,person,grayscale portrait of a confident young man wi...,What is the man's posture in the image?,He has his arms crossed.
1,dataset_images/pexels_person_1_0.jpg,https://images.pexels.com/photos/10078860/pexe...,pexels,person,grayscale portrait of a confident young man wi...,Is the image in color or black and white?,The image is in grayscale (black and white).
2,dataset_images/pexels_person_1_0.jpg,https://images.pexels.com/photos/10078860/pexe...,pexels,person,grayscale portrait of a confident young man wi...,What is the expression on the man's face?,He has a subtle smile.
3,dataset_images/pexels_person_1_0.jpg,https://images.pexels.com/photos/10078860/pexe...,pexels,person,grayscale portrait of a confident young man wi...,How would you describe the man's appearance?,He appears confident and young.
4,dataset_images/pexels_person_1_0.jpg,https://images.pexels.com/photos/10078860/pexe...,pexels,person,grayscale portrait of a confident young man wi...,What does the man's body language suggest?,His crossed arms and subtle smile suggest conf...

In [37]:
final_df

,image_path,image_url,source,topic,caption,question,answer
0,dataset_images/pexels_person_1_0.jpg,https://images.pexels.com/photos/10078860/pexe...,pexels,person,grayscale portrait of a confident young man wi...,What is the man's posture in the image?,He has his arms crossed.
1,dataset_images/pexels_person_1_0.jpg,https://images.pexels.com/photos/10078860/pexe...,pexels,person,grayscale portrait of a confident young man wi...,Is the image in color or black and white?,The image is in grayscale (black and white).
2,dataset_images/pexels_person_1_0.jpg,https://images.pexels.com/photos/10078860/pexe...,pexels,person,grayscale portrait of a confident young man wi...,What is the expression on the man's face?,He has a subtle smile.
3,dataset_images/pexels_person_1_0.jpg,https://images.pexels.com/photos/10078860/pexe...,pexels,person,grayscale portrait of a confident young man wi...,How would you describe the man's appearance?,He appears confident and young.
4,dataset_images/pexels_person_1_0.jpg,https://images.pexels.com/photos/10078860/pexe...,pexels,person,grayscale portrait of a confident young man wi...,What does the man's body language suggest?,His crossed arms and subtle smile suggest conf...
...,...,...,...,...,...,...,...
96125,dataset_images/unsplash_clock_1_29.jpg,https://images.unsplash.com/photo-151285624666...,unsplash,clock,grayscale photography of clock,Can you describe what is visible in the image?,The image shows grayscale photography of clock.
96126,dataset_images/unsplash_clock_1_29.jpg,https://images.unsplash.com/photo-151285624666...,unsplash,clock,grayscale photography of clock,What elements are clearly visible in the image?,The image clearly contains grayscale photograp...
96127,dataset_images/unsplash_clock_1_29.jpg,https://images.unsplash.com/photo-151285624666...,unsplash,clock,grayscale photography of clock,What stands out the most in this picture?,A notable feature in the image is grayscale ph...
96128,dataset_images/unsplash_clock_1_29.jpg,https://images.unsplash.com/photo-151285624666...,unsplash,clock,grayscale photography of clock,What can you infer from the scene?,It can be inferred that the image shows graysc...
96129,dataset_images/unsplash_clock_1_29.jpg,https://images.unsplash.com/photo-151285624666...,unsplash,clock,grayscale photography of clock,Describe the overall mood or scene of the image.,The overall scene reflects grayscale photograp...